name: Build and Test

on: [push]

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Fetch dependencies
      run: go get -d ./...

    - name: Build
      run: go build

  test:
    name: Test in nix-shell
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install Nix
      run: |
        curl https://nixos.org/nix/install | sh
        . ~/.nix-profile/etc/profile.d/nix.sh
        # Use latest stable nixpkgs channel
        nix-channel --add https://nixos.org/channels/nixos-19.09 nixpkgs
        nix-channel --update

    - name: Test
      env:
        INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
      run: |
        . ~/.nix-profile/etc/profile.d/nix.sh
        nix-shell --pure --keep INFURA_API_KEY --command 'go test -v ./...'
